### ISSUE TITLE
Packagist

### ISSUE THREAD

**Issue by adam-lynch** [Element-34/php-webdriver#29]
Would you mind putting this project on [Packagist](https://packagist.org/)?
We'd love to use [Composer](http://getcomposer.org/) to manage our use of this project a bit better (like we do with some others), to be sure which version we're using/have modified, etc.

All that's required is that a `composer.json` file is added at the root of the project containing a summary of the project, versions are tagged (`git tag -a 2.1.0 -m "tagging 2.1.0"` / `git tag -am "2.1.0"`) and that the GitHub service hook is set up. 
See the [Packagist about page](https://packagist.org/about) for more detail on each step.

**Comment by robertwe** [comment]
:+1: I would say do it ;)

**Comment by adam-lynch** [comment]
See my [pull-request](https://github.com/Element-34/php-webdriver/pull/32)

**Comment by adamgoucher** [comment]
in theory, its now at https://packagist.org/packages/element-34/php-webdriver -- though it isnt picking up the 1.7.0 tag i created.

**Comment by adam-lynch** [comment]
Thanks for merging that in! :+1: 

You should create the hook; from the [about page](https://packagist.org/about):

> Existing packages without auto-updating (GitHub hook) will be crawled once a day for updates. When the GitHub hook is enabled packages are crawled whenever you push, or at least once a week in case the crawl failed. You can also trigger a manual update on your package page if you are logged-in as a maintainer.
