### ISSUE TITLE
deleteWindow() doesn't work

### ISSUE THREAD

**Issue by velovint** [Element-34/php-webdriver#4]
Hi Element-34. I appreciate your work on WebDriver especially cleaning staff up, removing final classes and adding Wait class. I just switched to your source and found that you don't have deleteWindow() method in Session class for some reason, as a result call to Session::deleteWindow() fails with the following Exception

{{{
Exception: window is not a valid webdriver command.

PHPWebDriver/WebDriverBase.php:229
PHPWebDriver/WebDriverBase.php:199
}}}

**Comment by adamgoucher** [comment]
https://github.com/Element-34/php-webdriver/commit/e1fb421d467549a16d10e89474c8c68c7ed73c83
