### ISSUE TITLE
The next action is run before the page is loaded

### ISSUE THREAD

**Issue by mwytang** [Element-34/php-webdriver#41]
Each time I try running all my selenium actions, I get different results. Some times everything is successful, but sometimes elements cannot be found even though I did not change my code. The strangest thing is each time it is a different element that cannot be found. I find that the elements that are not found are the ones that are searched for right after a page reload. Is there a way other than putting a wait after each click of a button or link to make the script wait for the page to finishing loading before the next action is applied?

Thanks.

**Comment by adamgoucher** [comment]
In theory, you can look into setting an implicit wait

``` php
$this->session->implicitlyWait($number_of_seconds);
```

but this is, in general, a pretty horrible design pattern. Instead you should look into using explicit waits via the PHPWebDriver_WebDriverWait class which is described in the project readme.
