### ISSUE TITLE
Make php-webdriver work with saucelabs ondemand (and possibly versions were previously php-wedriver did not work)

### ISSUE THREAD

**Issue by OniOni** [Element-34/php-webdriver#5]
Currently, when a post request contains no data, curl sets the content size to -1. Unfortunatly, this causes some versions of selenium to just hang causing tests to fail.

Here is a diff of mod that just sets the content length to 0, if we are building a POST request with no data appended. 
https://gist.github.com/2727469

**Comment by adamgoucher** [comment]
this was merged in way back in https://github.com/Element-34/php-webdriver/commit/e43d85877eebf3cf457fedbb21c9d14aa01cba93
