### ISSUE TITLE
Fatal error: Class 'PHPWebDriver_WebDriverContainer' not found

### ISSUE THREAD

**Issue by eliasnogueira** [Element-34/php-webdriver#7]
Hello!
All the time when I execute more than once my script I receive this message:

"Fatal error: Class 'PHPWebDriver_WebDriverContainer' not found in /Users/eliasnogueira/test/PHPWebDriver/WebDriverElement.php on line 16"

I trying to run with a simple script like this:

``` php
require_once "PHPWebDriver/__init__.php";

$webdriver = new PHPWebDriver_WebDriver();

$session = $webdriver->session('firefox', array());
$session->implicitlyWait(10);

$session->open('http://www.tizag.com/htmlT/htmlselect.php');
$session->element("css selector","select[name='selectionField'] option[value='CO']")->click();

$session->close();
```

A weird workaround is replace the PHPWebDriver folder.
There's something that I need to do?

**Comment by adamgoucher** [comment]
I think I have fixed this accidentally; the script 'works for me'.
